In [18]:
def extract_digits(number):
    remaining_value = number
    digits = []
    while remaining_value > 0:
        digit = remaining_value % 10
        remaining_value = remaining_value//10
        digits.append(digit)
        print(digit, end=" ")
    print([i for i in reversed(digits)])


extract_digits(1_230)

0 0 3 2 1 [1, 2, 3, 0, 0]


In [19]:
# using divmod

def extract_digits(number):
    remaining_value = number
    while remaining_value > 0:
        remaining_value, digit = divmod(remaining_value, 10)
        print(f"remaining val: {remaining_value},\tdigit: {digit}")


extract_digits(78945)

remaining val: 7894,	digit: 5
remaining val: 789,	digit: 4
remaining val: 78,	digit: 9
remaining val: 7,	digit: 8
remaining val: 0,	digit: 7


In [45]:
# divisor
def find_proper_divisor(value):
    # 1- we want to know what are the proper devisors of a number
    # 2- we know that the number if divisible by itself
    # 3- we can use the modulo operator to see if the remainder equal 0 for all numbers than are less that the value
    # 4- we have to start checking the number less than half the value itself
    # 5- we know that all number are divisible by 1
    divisors = [1]
    for i in range(2, (value//2)+1):
        if value % i == 0:
            divisors.append(i)

    # using list comprehension helps to
    # shorter syntax, more readable and more efficient
    print(divisors)


def find_proper_divisor_optimized(value):
    divisors = [i for i in range(1, value//2+1) if not value % i]
    print("slightly faster", divisors)


find_proper_divisor_optimized(213)

slightly faster [1, 3, 71]


In [63]:
# prime numbers
# natural number > 1
# exclusively divisible by itself
def stop_loop():
    raise StopIteration


def potential_prime_n(n: int):
    # for i in range(2, n//2+1):
    #     if not n % i:
    #         print(n/i)
    #         return False
    # return True
    # faster
    return [(True) for i in range(2, n//2+1) if not n % i]


potential_prime_n(14)

[True, True]

# Sieve of Eratosthenes
---

This algorithm dates back to greek mathematician Sieve Of Eratosthenes. The whole think works as follows:
1. List all numbers starting at the value 2 up to the given maximum value.
2. All numbers are initially considered as potential candidates for prime numbers.
3. Then starting from the fist number `2` all numbers that are multiple of it are eliminated.
4. Then we move to the next number that has not been eliminated and all multiples of it are eliminated. 
5. This process is followed until there are not more numbers left


In [71]:
import math
import numpy as np
# Sieve of Eratosthenes

max_number = 50
all_numbers = np.arange(2, max_number+1)
prime_numbers = []

math.sqrt(49)

7.0

In [72]:

def SieveOfEratosthenes(num):
    prime = [True for i in range(num+1)]
    p = 2
    while (p * p <= num):

        # If prime[p] is not
        # changed, then it is a prime
        if (prime[p] == True):

            # Updating all multiples of p
            for i in range(p * p, num+1, p):
                prime[i] = False
        p += 1

    # Print all prime numbers
    for p in range(2, num+1):
        if prime[p]:
            print(p)


SieveOfEratosthenes(50)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


In [102]:
def sieve(n):
    flags = np.ones(n, dtype=bool)
    flags[0] = flags[1] = False
    for i in range(2, n):
        # We could use a lower upper bound for this loop, but I don't want to bother with
        # getting the rounding right on the sqrt handling.
        if flags[i]:
            flags[i*i::i] = False
    return np.flatnonzero(flags)


print(sieve(50))

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


In [8]:
import numpy as np


def sieve_of_eratosthenes(n):
    flags = np.ones(n, dtype=bool)
    flags[0:2] = False
    for i in range(2, len(flags)):
        if flags[i]:
            flags[i*i::i] = False
    print(np.flatnonzero(flags))


sieve_of_eratosthenes(45)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43]


# math exercises

In [7]:
# exercise 1
def cal(m, n):
    return (m*n//2) % 7

In [37]:
import numpy as np
# exercise 1b

# 1. count and sum numbers if divisible by 2 and 7
# 2. the user will enter the maximum value for this operation


def count_and_sum_div_7_n_2(max_value):
    counter = 0
    sum = 0
    numbers = list()
    for i in range(1, max_value+1):
        if i % 7 == 0 or i % 2 == 0:
            counter += 1
            sum += i
            numbers.append(i)
    return f"Total Numbers: {counter}\n Sum = {sum}", numbers


def count_and_sum_div_7_n_2_np(max_value):
    numbers = np.zeros(max_value, dtype=bool)
    numbers[2::2] = True
    numbers[7::7] = True
    filtered_nums = numbers.nonzero()[0]
    return sum(filtered_nums), len(filtered_nums)


count_and_sum_div_7_n_2_np(15)

(63, 8)

In [42]:
# exercise 1c:
def is_even(n):
    return n % 2 == 0


def is_odd(n):
    return n % 2 != 0


n = 1
"odd" if is_odd(n) and not is_even(n) else "even"

'odd'

In [99]:
# Exercise 2: Number as test

def number_as_test(n):
    num_to_text_dict = {
        0: "Zero",
        1: "One",
        2: "Two",
        3: "Three",
        4: "Four",
        5: "Five",
        6: "Six",
        7: "Seven",
        8: "Eight",
        9: "Nine",
    }
    text = []
    if n == 0:
        return "Zero"
    while n > 0:
        remainder = n % 10
        n //= 10
        text.append(num_to_text_dict[int(remainder)])
    return " ".join(reversed(text))


number_as_test(100)

'One Zero Zero'

In [108]:
# improved version
import pytest


def map_number_to_text(number):
    num_to_text_dict = {
        0: "Zero", 1: "One", 2: "Two", 3: "Three", 4: "Four",
        5: "Five", 6: "Six", 7: "Seven", 8: "Eight", 9: "Nine",
    }
    return num_to_text_dict[number]


def number_as_text(n):
    num_as_text = ""
    remaining_value = n
    while remaining_value > 0:
        remaining_value, remainder = divmod(remaining_value)
        num_as_text += map_number_to_text(remainder) + " " + num_as_text
    return num_as_text
# number_as_test(101123456789)


@pytest.mark.parametrize("n, expected",
                         [(7, "SEVEN"),
                          (42, "FOUR TWO"),
                          (7271, "SEVEN TWO SEVEN ONE"),
                          (24680, "TWO FOUR SIX EIGHT ZERO"),
                          (13579, "ONE THREE FIVE SEVEN NINE")])
def test_number_as_text(n, expected):
    assert number_as_text(n) == expected
# test_number_as_text()

In [125]:
# exercise 3: Perfect Numbers
# A natural number is called a perfect number
# If value == sum(of its real divisors)

# 1. find real divisors of a number

def perfect_number(n):
    perfect_n = n
    sum_p_n = 0
    while n > 1:
        perfect_n /= 2


perfect_number(6)

62.5

In [34]:
import numpy as np
# 2.2.4 Exercise 4: Prime Numbers
# write a function to compute all prime numbers up to a given value.
# prime number is a natural number greater than 1 and exclusively divisible by itself and 1


def erase_no_primes(is_potentially_prime, number):
    for n in range(number+number, len(is_potentially_prime), number):
        is_potentially_prime[n] = False


def get_prime_numbers(is_prime):
    prime_numbers = []
    for i in range(2, len(is_prime)):
        if is_prime[i]:
            prime_numbers.append(i)
    return prime_numbers


def calc_primes_up_to_max(max_value):
    is_potentially_prime = [True for _ in range(1, max_value + 2)]
    for i in range(2, max_value//2+1):
        if is_potentially_prime[i]:
            erase_no_primes(is_potentially_prime, i)
    return get_prime_numbers(is_potentially_prime)


calc_primes_up_to_max(50)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

In [49]:
import itertools
# 2.2.4 optimization


def erase_multiples_of_current(values, number):
    for n in range(number*number, len(values), number):
        values[n] = False


def calc_primes_up_to_max_v2(max_value):
    is_potential_prime = [True for _ in range(1, max_value + 2)]
    for number in range(2, (max_value//2 + 2)):
        if is_potential_prime[number]:
            erase_multiples_of_current(is_potential_prime, number)
    is_potential_prime[0:2] = False, False
    return list(itertools.compress(range(len(is_potential_prime)), is_potential_prime))


print(calc_primes_up_to_max_v2(2))

# Using numpy is more elegant and efficient


def calc_primes_up_to_max_np(max_value):
    arr = np.ones(max_value+1, bool)
    arr[0] = False
    arr[1] = False
    for i in range(2, max_value):
        if arr[i]:
            arr[i*i::i] = False
            # print(i, arr)
    return list(np.flatnonzero(arr))


calc_primes_up_to_max_np(50)

[2]


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

In [1]:
import numpy as np


def cal_prime_numbers_up_to_max(max_n):

    potential_primes = np.ones(max_n+1, dtype=bool)

    potential_primes[0:2] = False

    for i in range(2, max_n//2+1):

        if potential_primes[i]:

            potential_primes[i*i::i] = False

    return np.flatnonzero(potential_primes)


cal_prime_numbers_up_to_max(100)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64)

In [16]:
import itertools
# exercise 5: Prime Number Pairs
# Twin: is_prime(n) & is_prime(n+2)
# Cousin: is_prime(n) & is_prime(n+4)
# s: is_prime(n) & is_prime(n+6)


def find_all_multiples(values, n):
    for i in range(n*n, len(values), n):
        values[i] = False
# to optimize code first i will start by calculating all prime numbers up to max number


def cal_all_prime_numbers(max_number):
    potential_prime_numbers = [True for _ in range(1, max_number+7)]
    for i in range(2, max_number//2+7):
        if potential_prime_numbers[i]:
            find_all_multiples(potential_prime_numbers, i)

    potential_prime_numbers[0:2] = False, False
    result = itertools.compress(
        range(len(potential_prime_numbers)), potential_prime_numbers)
    return tuple(result)

# def pair_conditions()


def is_prime(primes, n):
    return n in primes


def find_pairs_of_prime_numbers(max_n):
    pairs = {"twin": {}, "cousin": {}, "s": {}}
    prime_numbers = cal_all_prime_numbers(max_n+7)

    def is_twin_pair(n):
        return is_prime(prime_numbers, n) and is_prime(prime_numbers, n+2)

    def is_cousin_pair(n):
        return is_prime(prime_numbers, n) and is_prime(prime_numbers, n+4)

    def is_s_pair(n):
        return is_prime(prime_numbers, n) and is_prime(prime_numbers, n+6)

    pairs["twin"] = {i: i + 2 for i in range(1, max_n) if is_twin_pair(i)}
    pairs["cousin"] = {i: i + 4 for i in range(1, max_n) if is_cousin_pair(i)}
    pairs["s"] = {i: i + 6 for i in range(1, max_n) if is_s_pair(i)}
    return pairs


find_pairs_of_prime_numbers(50)

{'twin': {3: 5, 5: 7, 11: 13, 17: 19, 29: 31, 41: 43},
 'cousin': {3: 7, 7: 11, 13: 17, 19: 23, 37: 41, 43: 47},
 's': {5: 11,
  7: 13,
  11: 17,
  13: 19,
  17: 23,
  23: 29,
  31: 37,
  37: 43,
  41: 47,
  47: 53}}

In [20]:

# exercise 5: Prime Number Pairs (Optimization)
def find_all_multiples_of_n(potential_prime_numbers, n):
    for i in range(n*n, len(potential_prime_numbers), n):
        potential_prime_numbers[i] = False


def cal_all_primes_up_to_max(max_number):
    # create potential prime numbers add extra 7 numbers to account for checking pairs
    potential_prime_numbers = [True for _ in range(max_number+7)]
    for i in range(2, max_number//2+2):
        if potential_prime_numbers[i]:
            find_all_multiples_of_n(potential_prime_numbers, i)
    # set 0 and 1 as non prime numbers
    potential_prime_numbers[:2] = False, False
    return tuple(itertools.compress(range(len(potential_prime_numbers)), potential_prime_numbers))


def filter_pairs(n, next_number, prime_numbers):
    if n in prime_numbers and next_number in prime_numbers:
        return True
    return False


def form_prime_pairs(max_number):
    prime_numbers = cal_all_primes_up_to_max(max_number)
    pairs = {'twin': {}, 'cousin': {}, 's': {}}
    for i in range(1, max_number):
        if filter_pairs(i, i+2, prime_numbers):
            pairs['twin'][i] = i+2
        if filter_pairs(i, i+4, prime_numbers):
            pairs['cousin'][i] = i+4
        if filter_pairs(i, i+6, prime_numbers):
            pairs['s'][i] = i+6
    return pairs


form_prime_pairs(50)

{'twin': {3: 5, 5: 7, 11: 13, 17: 19, 29: 31, 41: 43},
 'cousin': {3: 7, 7: 11, 13: 17, 19: 23, 37: 41, 43: 47},
 's': {5: 11,
  7: 13,
  11: 17,
  13: 19,
  17: 23,
  23: 29,
  31: 37,
  37: 43,
  41: 47,
  47: 53}}